
###
POST http://localhost:5000/addition
Content-Type: application/json

{
"number1": 1,
"number2": 3
}

###
POST http://localhost:5000/subtraction
Content-Type: application/json

{
"number1": 1,
"number2": 2
}

###
POST http://localhost:5000/multiplication
Content-Type: application/json

{
"number1": 1,
"number2": 3
}

###
POST http://localhost:5000/division
Content-Type: application/json

{
"number1": 1,
"number2": 21
}
###
POST http://localhost:5000/addMultipleNumbers
Content-Type: application/json

{"numbers": [1, 2, "3"]}